### ISSUE TITLE
Inconsistent collision detection inside self-referencing sectors

### ISSUE THREAD

**Issue by derekmd** [zokum-no/zokumbsp#19]
This covers deep water and 3D bridges using a sector that references itself on both sides of all its linedefs. With ZenNode, I always used command line option `-nu` along with a .zen file to prevent extra subsectors that would cause floating floors to not work.

```
zennode.exe -nu -nq -rz ladder.wad -o ladder.wad
```

But running the same in ZokumBSP, the player is able to fall into the middle of the self-referencing sector.

```
zokumbsp.exe -nu -nq -rz ladder.wad -o ladder.wad
```

# Example

This demo map shows a ladder where you approach the floating sectors from side. You can see the player can walk through some segments of the ladder sectors.

**ladder.wad**: [download ladder.zip](https://github.com/zokum-no/zokumbsp/files/4426776/ladder.zip)

**ladder.zen** placed in the same directory.

```
[MAP01]

[unique-sectors]
28
22
40
38
8
39
7
25

[dont-split-sectors]
28
22
40
38
8
39
7
25
```

# [Updated] Example with unique sectors

Here is an update of the above WAD. This one has only rectangle and triangle shapes for the unique floating floors. Each polygon is unique. i.e., no joined sectors that need splitting by the nodesbuilder to form subsectors.

[ladder-unique.zip](https://github.com/zokum-no/zokumbsp/files/4446092/ladder-unique.zip)

# Example from a Released WAD

https://www.doomworld.com/idgames/levels/doom2/d-f/dyst3 MAP11 (released 1996) has one of the first double 3D bridges in a doom2.exe map.

```
zokumbsp.exe -nu -nq -rz e:\doom2\wads\dyst3lev.wad MAP11 -o e:\doom2\wads\dyst3lev.wad
```

Players fall through the bridge on both the first and second story.

# Related commit

In https://github.com/zokum-no/zokumbsp/commit/9833ef241d666b70a6532d4e499992e0028407d0 ("Fixes to -nu handling to ensure invisible floors work") I'm curious if you remember what maps you tested? Alien Vendetta?

**Comment by VigilantDoomer** [comment]
The #9833ef2 version seems exactly to be the first one causing this bug on another map I have tested (I signed up for github because I've experienced that multi-tree and maps with self-referencing sectors are broken in later versions, and is going to open a separate issue for multi-tree).
I mean, I've actually tried building a specific map I have with different versions and located #9833ef2 as the culprit for breaking self-referencing sector effects.
What's more, since that version it seems that one has to specify -nu- instead and then it will work. Didn't try on your map though yet.

**Comment by derekmd** [comment]
After speaking with Zokum, I found a couple workarounds. Mappers can't assume ZokumBSP is a drop-in replacement for ZenNode behaviour. To get floating sectors working, you have to either:

1. Build the nodes with another builder, then use ZokumBSP only for blockmap compression.
  ```
  zokumbsp.exe -n- -r- in.wad
  ```
2. Or tag all self-referenced linedefs of the floating sector with tag 998. From the docs:

   > 04:03 No render tag for linedef - 'tag 998'
   > -------------------------------------------
   > 
   > By setting the tag to 998 on a linedef, this line will not be rendered by the
   > Doom engine. More specifically, this will not create a seg out of that
   > linedef. This can be used to add impassible lines and manually simplified
   > geometry.

   ![tag-998](https://user-images.githubusercontent.com/823566/78970037-65ef6800-7ad6-11ea-8ad6-34b840112505.png)

**Comment by zokum-no** [comment]
This is an oversight / bug I will correct. To optimize blockmaps I remove lines that do not have height differences on both sides to to being the same sector and do not have a linedef special.

There is no need to use 998 specifically, just something that makes it not trigger this problematic optimization. You can use any tag but 999.

I have plans on cleaning this up a bit to make it more versatile and less hackish.

**Comment by XaserAcheron** [comment]
Did this ever get addressed? I'm still seeing the MAP01 optimization in the code [here](https://github.com/zokum-no/zokumbsp/blob/95b03802b0967f2f265833787a7e6d18563ed8dc/src/zokumbsp/preprocess.cpp#L578) and it looks like the option for it (RemoveNonCollidable) is enabled by default if I'm reading the code correctly; if I missed a spot then my bad, mostly doing a quick-ish skim here.

ATM this is the _one_ thing that stops me from recommending zokumbsp as a drop-in replacement for zennode, since it'll bork up self-referencing sectors unless folks know how to unset the flag.

**Comment by zokum-no** [comment]
I'm at work, and going away for the weekend. I might be able to look into it in the brief period I have between coming home and going away.

I know I changed some flags to enable certain optimizations as off by default in the latest version and I will check if this is one of them. It is important that self-referencing sectors work out of the box.

**Comment by zokum-no** [comment]
Ok, I need to reboot and configure virtual cpu stuff in the BIOS to get virtualbox to run on my new hardware. Without that up and running it is fairly hard for me to look at the code. In the meantime, try -ni- Here is from the manual:

08:04 'i' - Ignore non-visible lineDefs
---------------------------------------

This option is similar to a blockmap option that removes non-collidable lines
from the level geometry. It does however check for the presence of a middle
texture, since those need to be rendered even if a linedef has sidefs
belonging to the same sector. This will also check for the presence of a lower
texture to avoid these lines to be ignored when designig maps with invisible
floors.

I'm not sure that fixes it, but it seems to be that this is the problematic switch. With a dummy lower texture that is never rendered, the problem should be avoided. If it still breaks, this is a bug.

This is done so that it can enable the optimization in the spots you need it and allow for special marking of the self ref sectors. Detecting self-ref sectors could quickly get buggy with control sectors involved.

I should definitely rewrite the manual entry for this one! It is clearly misleading...

**Comment by zokum-no** [comment]
It's been taking a bit longer than expected to set up my new dev environment, but I  am working on it.
